config/routes.rb
OmniSpeedDating::Application.routes.draw do
  get "home/landing"

  get "home" => "home#index"
  get "logout" => "home#logout"
  get "admin" => "home#admin"
  get "events" => "home#events"

  resource "profile"

  %w(get post).each do |method|
    send(method, '/auth/:provider/callback', to: 'sessions#create')
  end

  root :to => 'home#landing'

end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body

  def gender_string
    "Not set"
  end

  def orientation_string
    "Not set"
  end

  class << self

    def find_or_create_from_auth_hash(user_data)
      u = User.find_by_provider_and_uid(user_data[:provider], user_data[:uid])
      if u.nil?
        u = User.create().tap do |u|
          u.uid = user_data[:uid]
          if user_data.has_key?(:info)
            u.name = user_data[:info][:name]
            u.email = user_data[:info][:email]
          else
            u.name = user_data[:name]
            u.email = user_data[:email]
          end
          u.provider = user_data[:provider]
          if u.name.nil?
            u.name = u.uid
          end
          u.save
        end
      end
      u
    end

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  before_filter :authenticate_user!

  private

  def authenticate_user
    if current_user.nil? and !auth_hash.nil?
      current_user = User.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
    end
  end

  def authenticate_user!
    authenticate_user
    redirect_to "/auth/#{auth_provider}" unless current_user
  end

  def deauthenticate_user!
    session['current_user'] = nil
    @current_user = nil
    redirect_to '/'
  end

  def auth_provider
    Rails.env == "production" ? "facebook" : "developer"
  end
 
  def auth_hash
    request.env["omniauth.auth"]
  end

  def current_user=(user)
    @current_user = user
    session['current_user'] = @current_user ? @current_user.uid : nil
  end

  def current_user
    @current_user ||= session['current_user'] ? User.find_by_uid(session['current_user']) : nil
  end

  def logged_in?
    return !current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [ :landing, :logout ]
  before_filter      :deauthenticate_user!, :only => [ :logout ]
  before_filter      :authenticate_user, :only => [ :landing ]

  def index
    redirect_to :landing unless logged_in?
  end

  def landing
    if logged_in?
      redirect_to :home
    else
      render :layout => "landing"
    end
  end

  def logout
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
  end

  def edit
  end

  def create
    redirect_to profile_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [ :create ]
  skip_before_filter :verify_authenticity_token, :only => [ :create ]

  def create
    return permission_denied unless auth_hash
    user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = user
    redirect_to '/'
  end

  protected

  def permission_denied
    render :file => "public/401.html", :status => :unauthorized
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for :title, page_title.to_s
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= title "Home"

%h1 
  Welcome to your Omni Speed Dating homepage,
  %span{id: "username"}= current_user.name

app/views/home/landing.html.haml
%div.center
  %h1 Welcome to Omni Speed Dating
  %div
    %a{:id => "login", :href => "/home"} Login

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} X
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "Omni Speed Dating #{content_for?(:title) ? ' - ' + yield(:title) : ''}"
    %meta{:content => content_for?(:description) ? yield(:description) : "Omni Speed Dating", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)

  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
      %a.brand{:href => "/"} Omni Speed Dating
    #main{:role => "main"}
      .container
        = render 'layouts/messages'
        = render 'shared/nav'
        %div.center
          = yield
          %div
            = link_to "Logout", logout_path, :id => "logout"
      %footer

app/views/layouts/landing.html.haml
!!! 5
%html
  %head
    %title= "Omni Speed Dating #{content_for?(:title) ? ' - ' + yield(:title) : ''}"
    %meta{:content => content_for?(:description) ? yield(:description) : "Omni Speed Dating", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)

  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      %nav.navbar-inner
        .container
      %a.brand{:href => "/"} Omni Speed Dating
    #main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
      %footer

app/views/profiles/edit.html.haml
= title "Profile"

%h1 
  Edit your profile
%div.content
  = form_tag profile_path do
    %b Gender
    %br
    %b Orientation
    %br
    = button_tag "Save"

app/views/profiles/show.html.haml
= title "Profile"

%h1 
  Welcome to your Profile,
  %span{id: "username"}= current_user.name
%div.content
  Current profile setting:
  %br
  %b Gender
  = current_user.gender_string 
  %br
  %b Orientation
  = current_user.orientation_string
  %br
  = link_to "Edit", edit_profile_path 

app/views/shared/_nav.html.haml
%div.topbar
  %div.icon icon
  %div.navitem
    = link_to "Profile", profile_path
  %div.navitem
    = link_to "Admin", admin_path
  %div.navitem
    = link_to "Events", events_path